### ISSUE TITLE
doesn't sense all tarfiles?

### ISSUE THREAD

**Issue by bronson** [minad/mimemagic#1]
MimeMagic.by_magic isn't able to sense either file on this page as a tarfile:  http://www.vim.org/scripts/script.php?script_id=1729

However, both tar and the Unix file utility like them.

```
$ wget http://www.vim.org/scripts/download_script.php?src_id=6516 -O tt.tar
$ file tt.tar      => tt.tar: tar archive
```

in irb:

```
require 'open-uri'
require 'mimemagic'
x = open('http://www.vim.org/scripts/download_script.php?src_id=6516')
MimeMagic.by_magic(x)    => nil
x = open('http://www.vim.org/scripts/download_script.php?src_id=2877')
MimeMagic.by_magic(x)    => application/x-tar 
```

(the last 2 are just to prove that mimemagic does sense other tarfiles)

Just fyi, mimemagic is serving me great.

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
