### ISSUE TITLE
Yanking previous versions on Rubygems

### ISSUE THREAD

**Issue by sunny** [minad/mimemagic#103]
Hi @minad, Thank you for maintaining mimemagic!

I have seen builds suddenly failing because mimemagic versions prior to 0.3.5 have been removed from rubygems.org.

Is there a security issue that we should be aware of that required these yanks?

**Comment by minad** [comment]
Duplicate of #98

**Comment by sunny** [comment]
Oh, sorry for not seeing that closed one. Good luck handling all the follow-up issues and comments.
