### ISSUE TITLE
Fix license documentation

### ISSUE THREAD

**Issue by Silex** [minad/mimemagic#152]
Hello,

In https://github.com/mimemagicrb/mimemagic/blob/master/README.md and also on the github repository we see that the licence is MIT. But apparently it's not it's GPL.

Please fix the documentation/github description.

**Comment by Nytelife26** [comment]
Looking at [LICENSE](https://github.com/mimemagicrb/mimemagic/blob/master/LICENSE), it is most definitely still using MIT. It was changed briefly to the GPL following a short issue with `shared-mime-info`, and then changed back when the GPL code was pulled.

In short, the GPL is harmful to ecosystems.

**Comment by Silex** [comment]
After the whole mess with rails breaking all over the place I'm now confused, can I keep the mimemagic gem or not? :laughing: 

I have some old app that links to `3.3` which is apparently deleted.

**Comment by Nytelife26** [comment]
> can I keep the mimemagic gem or not?

Yes.

> I have some old app that links to `3.3` which is apparently deleted.

It is, they got yanked because they contained license incompatible code.

And I don't know why people are disliking my comment. I guess they're still all for the GPL despite all the harm it has caused.
