### ISSUE TITLE
test/files/images.* considered non free

### ISSUE THREAD

**Issue by boutil** [minad/mimemagic#22]
Hi,

The files test/files/images.* used in test comes from https://commons.wikimedia.org/wiki/File:Phalaenopsis_%28aka%29.jpg which are licensed under the CC-BY-SA-2.5. This license is considered non free by the Debian project, and because of that, your project cannot be packaged and distributed as is in this GNU/Linux distribution (and others).

Since the content of the image in itself does not seem to play a role, would you consider using instead an image licensed under CC-BY-SA-3.0 or CC-BY-SA-4.0, which is considered free?

Thanks in advance!

Cédric

**Comment by minad** [comment]
yes, sure. could you create a pull request? maybe just use a public domain image
