### ISSUE TITLE
Can't identify Photoshop PSD files with `by_magic`

### ISSUE THREAD

**Issue by airblade** [minad/mimemagic#24]
I have a Photoshop PSD file and MimeMagic's `by_magic` method doesn't identify it.

```ruby
pry(main)> require 'mimemagic'
true
pry(main)> f = File.open 'LBT-73-15-046_cuff_rings_blue.jpg.psd'
#<File:LBT-73-15-046_cuff_rings_blue.jpg.psd>
-rw-r--r--@ 1 andy  andy  85185  4 Aug 10:21 LBT-73-15-046_cuff_rings_blue.jpg.psd
pry(main)> MimeMagic.by_magic f
nil
```

A little debugging shows that [`magic_match_io`](https://github.com/minad/mimemagic/blob/v0.3.0/lib/mimemagic.rb#L87) is returning `nil`.

However `by_extension` does identify it:

```ruby
pry(main)> MimeMagic.by_extension 'psd'
#<MimeMagic:0x007ff6242eaaf0 @type="image/vnd.adobe.photoshop", @mediatype="image", @subtype="vnd.adobe.photoshop">
```

I'm not familiar with how this gem is supposed to be used so please excuse any silly questions:

- would you expect `by_magic` to identify the file here?
- if not, would you expect callers to chain the various identification methods, e.g:

```ruby
type = MimeMagic.by_magic(f) || MimeMagic.by_extension(f)
```

Many thanks in advance.

**Comment by minad** [comment]
I would recommend to use by_extension first, I think psd is quite unique. I don't know if the freedesktop mime database would detect the psd correctly by looking into the file
