### ISSUE TITLE
Publish gem changes to rubygems

### ISSUE THREAD

**Issue by joshleaves** [minad/mimemagic#28]
Hi @minad,

Could you please release a new version? I am using paperclip and I happened to stumble upon a png that contained "xl\" in its first 2K characters...thus mistaking it for "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" instead of "image/png". New rules are fine from my usage.

Thanks

**Comment by minad** [comment]
sure but paperclip has an exact version constraint 3.0.0
