### ISSUE TITLE
Misdetection of CSV file mime-type

### ISSUE THREAD

**Issue by jastkand** [minad/mimemagic#29]
I'm using paperclip gem which uses mimemagic gem for mime-type detection. I have the problem with detection of mime-type of CSV file type. The content of the file is like this

```csv
candidate_id,email
1,some@email.com
```

The mime-type of a file with such content is misdetected with `image/x-quicktime` because of this rule https://github.com/minad/mimemagic/blob/master/lib/mimemagic/tables.rb#L1717

As we can see the rule defines to return `image/x-quicktime` if the file has `idat` pattern on the 4th position of the file. Can we fix this somehow?

For now as a temporary workaround I have just removed this type in initializer file

```ruby
MimeMagic.remove('image/x-quicktime')
```

**Comment by minad** [comment]
Some files are just hard to detect, so I don't think there is a fix. Can you use the file extension?

**Comment by jastkand** [comment]
Unfortunately this gem is used by paperclip gem, so I cannot change the behavior of the last one to use file extension. Thanks anyway for great API of mimemagic gem which allows to remove some rules which doesn't work for some tasks and to define ones that work. It's very handy.
