### ISSUE TITLE
xlsx/docx code breaks some jpegs

### ISSUE THREAD

**Issue by glebtv** [minad/mimemagic#33]
[1] pry(main)> MimeMagic.by_magic(File.open(Rails.root.join('thumb1.jpg'))).type
=> "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

![thumb1](https://cloud.githubusercontent.com/assets/1041407/14157157/80cd7108-f6d2-11e5-94bd-bcbdf70ee09b.jpg)

removing this hack:
https://github.com/minad/mimemagic/blob/master/lib/mimemagic/overlay.rb
fixes it. It seems to be looking in N first bytes of file for PK, when it should look at only first two bytes.

[1] pry(main)> MimeMagic.by_magic(File.open(Rails.root.join('thumb1.jpg'))).type
=> "image/jpeg"

**Comment by glebtv** [comment]
![50044344b](https://cloud.githubusercontent.com/assets/1041407/14862153/d979a3ac-0cb8-11e6-90a2-1a5dc1a72279.jpg)

This is not a one-time problem
[1] pry(main)> MimeMagic.by_magic(File.open('/home/gleb/Downloads/50044344b.jpg'))
=> #<MimeMagic:0x00000005a66440
 @mediatype="application",
 @subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet",
 @type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
