### ISSUE TITLE
MimeMagic.by_magic detects JavaScript files with 'use strict' as x-perl

### ISSUE THREAD

**Issue by danielbreves** [minad/mimemagic#34]
I'm using paperclip to store JavaScript attachments on a Rails app. Paperclip [recently started using MimeMagic to detect content-type](https://github.com/thoughtbot/paperclip/commit/2a0274d16b4c143f2948662455e2277d49888705) and this caused a bug.

cc @scpike

**Comment by ocke** [comment]
https://github.com/minad/mimemagic/pull/35

**Comment by scpike** [comment]
This is probably a bug in the shared-mime-info project's list (https://cgit.freedesktop.org/xdg/shared-mime-info/tree/freedesktop.org.xml.in?id=Release-1-5#n3066). Can you open a bug ticket with them? 

I don't think this project wants to get into maintaining a fork of that table list (but that's for @minad to decide). 

In the meantime, I think you can "fix" this in paperclip with judicious use of `Mimemagic.remove` (https://github.com/minad/mimemagic/blob/master/lib/mimemagic.rb#L35). You might also look at `Mimemagic#text?`. Paperclip uses the content types for validation for security purposes, but possibly it should have an option for allowing all text-types.

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
