### ISSUE TITLE
PDF magic in 0.1.8 is too loose

### ISSUE THREAD

**Issue by bronson** [minad/mimemagic#4]
I'm stuck on mimemagic 0.1.7 because of the new PDF magic.

[This change](https://github.com/minad/mimemagic/commit/50078a4d52bb80f525784f6a4cb874fc7d2a03a0#L0L1462) is the problem:

    -    ['application/pdf', [[0, "%PDF-"]]],
    +    ['application/pdf', [[0..1024, "%PDF-"]]],

Turns out LOTS of files have %PDF- in the first 1024 bytes.  Here are two:

* a [text file](http://www.vim.org/scripts/script.php?script_id=1674)
* a [zipfile](http://www.vim.org/scripts/script.php?script_id=2906)

Is there a way to report this broken magic upstream?

(I originally commented [on the commit](https://github.com/minad/mimemagic/commit/50078a4d52bb80f525784f6a4cb874fc7d2a03a0#commitcomment-280266))

**Comment by minad** [comment]
Still an issue?

We now have mimemagic/overlay, but I would prefer upstream fixes.

**Comment by bronson** [comment]
Hi, sorry I missed this.  Yep, still an issue:

https://github.com/minad/mimemagic/blob/master/lib/mimemagic/tables.rb#L1522

I'll add an overlay if needed, thanks!  So far, remaining on 0.1.7 has been fine.
