### ISSUE TITLE
Add Outlook .msg files

### ISSUE THREAD

**Issue by lloeki** [minad/mimemagic#44]
mime type: `application/vnd.ms-outlook`
extension: `.msg`
possible magic bytes: `D0 CF 11 E0 A1 B1 1A E1`

**Comment by McRip** [comment]
`
MimeMagic.add(
  'application/vnd.ms-outlook',
  extensions: 'msg',
  magic:      [
    [0, "\320\317\021\340\241\261\032\341".force_encoding('ASCII-8BIT')],
    [0, "\320\317\021\340".force_encoding('ASCII-8BIT')]
  ],
  parents:    ['x-ole-storage'],
  comment:    ['MS Outlook msg File']
)
`

**Comment by saghaulor** [comment]
Please consider merging this.

**Comment by saghaulor** [comment]
Actually, @McRip's suggestion makes it so that all Microsoft Office files are identified as Outlook files. So proceed with caution.

**Comment by McRip** [comment]
Sorry, it was just the configuration @lloeki provided adapted as MimeMagic configuration.
Worked for me, but i didn't check if other office files are also affected. Seems like we have to adjust the magic bytes if possible.

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
