### ISSUE TITLE
Doesn't recogonize Apple .pages and some .docx

### ISSUE THREAD

**Issue by longobongo** [minad/mimemagic#45]
Hi there, hen I submit an Apple .pages file or certain .docx files, it comes back as application/zip despite including mimemagic/overlay, any ideas why? Attached are the files in question.
[unknown_files.zip](https://github.com/minad/mimemagic/files/517166/unknown_files.zip)

edit: also some extra context, the docx file was created by opening up a Google doc and selecting 'download as docx'.

**Comment by plicjo** [comment]
This looks like the same issue as https://github.com/minad/mimemagic/issues/39

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
