### ISSUE TITLE
Adobe Photoshop files are not detected correctly by magic

### ISSUE THREAD

**Issue by conf** [minad/mimemagic#47]
It seems PSD files are not detected correctly.

Minimal reproduction steps:

1. Unzip attached archive
2. Run the following code

```ruby
MimeMagic.by_magic(File.open('arrows.psd')) # => nil
```

Expected:
The code above should return `image/vnd.adobe.photoshop'`

Actual:
The code above returns `nil`.

Tested with mimemagic-0.3.2, macOS Sierra.

[arrows.zip](https://github.com/minad/mimemagic/files/568486/arrows.zip)

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
