### ISSUE TITLE
ZIP file detected as PDF

### ISSUE THREAD

**Issue by lordofthelake** [minad/mimemagic#49]
The attached ZIP file with 2 PDF files inside is recognised by MimeMagic 0.3.2 as `application/pdf`, while `file -I` recognises it correctly as `application/zip`.

Inspecting the ZIP file contents, it can be seen that the `PK\003\004` token is present at the start, while `%PDF-` can be found in the contents.

So, according to the `freedesktop.org.xml` file, two rules would be applicable:

PDF:
```xml
<mime-type type="application/pdf">
    <_comment>PDF document</_comment>
    <acronym>PDF</acronym>
    <expanded-acronym>Portable Document Format</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match type="string" value="%PDF-" offset="0:1024"/>
    </magic>
    <glob pattern="*.pdf"/>
    <alias type="application/x-pdf"/>
    <alias type="image/pdf"/>
    <alias type="application/acrobat"/>
</mime-type>
```

ZIP: 
```xml
<mime-type type="application/zip">
    <_comment>Zip archive</_comment>
    <alias type="application/x-zip-compressed"/>
    <alias type="application/x-zip"/>
    <generic-icon name="package-x-generic"/>
    <magic priority="40">
      <match type="string" value="PK\003\004" offset="0"/>
    </magic>
    <glob pattern="*.zip"/>
</mime-type>
```

The ZIP rule has priority 40, so I'm inferring – and correct me if I'm wrong – that it should have higher priority than the PDF rule (priority 50).

Looking at the generated table, though, the rules have inverse order:
- PDF @ line 1503: https://github.com/minad/mimemagic/blob/v0.3.0/lib/mimemagic/tables.rb#L1503
- ZIP @ line 1789: https://github.com/minad/mimemagic/blob/v0.3.0/lib/mimemagic/tables.rb#L1789

This would explain gem's behaviour. Is my reasoning correct? Might this be a bug in the tables generation script?

[sample.zip](https://github.com/minad/mimemagic/files/589521/sample.zip)

**Comment by plicjo** [comment]
@lordofthelake You closed this but it hasn't been merged into this repository yet.

**Comment by lordofthelake** [comment]
@plicjo I think that the our internal PR had an intended side-effect, closing this issue wasn't intended

**Comment by plicjo** [comment]
Ok, no problem!

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
