### ISSUE TITLE
.xls file detected as application/x-ole-storage

### ISSUE THREAD

**Issue by jaredmoody** [minad/mimemagic#50]
I'm having an issue with an .xls file being detected as application/x-ole-storage when using `by_magic`:

```
> file -I test.xls
test.xls: application/vnd.ms-excel; charset=binary
```

```
> MimeMagic.by_magic(File.open("test.xls"))
=> #<MimeMagic:0x007fb76df72ea8 @type="application/x-ole-storage", @mediatype="application", @subtype="x-ole-storage">

> MimeMagic.by_path("test.xls")
=> #<MimeMagic:0x007fb76df98c98 @type="application/vnd.ms-excel", @mediatype="application", @subtype="vnd.ms-excel">
```

Is this a bug or how can I get MimeMagic to recognize the file as `application/vnd.ms-excel` ?

**Comment by siannopollo** [comment]
I'm having the same issue. Word docs return the proper mime type, but not Excel files. Here's the monkey-patch I'm using until this get's resolved (but based on the most recent commit being Aug 9, 2016, I'm not expecting that to happen any time soon):

``` ruby
Paperclip::ContentTypeDetector.class_eval do
  def type_from_file_contents_with_excel_exception
    type = type_from_file_contents_without_excel_exception
    types = possible_types
    return types.first if type == 'application/x-ole-storage' && types.include?('application/vnd.ms-excel')
    type
  end
  alias_method_chain :type_from_file_contents, :excel_exception
end
```

**Comment by kevinzwhuang** [comment]
The same thing happens to `.ppt` files:

```ruby
 [2] pry(main)> MimeMagic.by_magic(File.open('sample.ppt'))
 => #<MimeMagic:0x007f91b22b6d80 @mediatype="application", @subtype="x-ole-storage", @type="application/x-ole-storage">


 [3] pry(main)> MimeMagic.by_path('sample.ppt')
 => #<MimeMagic:0x007f91b10c0f40 @mediatype="application", @subtype="vnd.ms-powerpoint", @type="application/vnd.ms-powerpoint">
```

**Comment by bewatts** [comment]
Same this is happening to `.doc` files

[5] pry(main)> MimeMagic.by_magic(File.open('/users/pivotal/Documents/test.doc'))
=> #<MimeMagic:0x007fdb3eb8f008 @mediatype="application", @subtype="x-ole-storage", @type="application/x-ole-storage">
[6] pry(main)> MimeMagic.by_path('/users/pivotal/Documents/test.doc')
=> #<MimeMagic:0x007fdb3eb345e0 @mediatype="application", @subtype="msword", @type="application/msword">

**Comment by bewatts** [comment]
Here another patch based on @siannopollo's work above.  It uses Module.prepend instead of alias_method_chain.  Checkout this [link](http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/) if you'd like an analysis of Module.prepend vs alias_method_chain. 


```ruby
module ContentTypeDecectorHack
  FILE_TYPE_TO_HAC = 'application/msword'
  def type_from_file_contents
    type = super
    types = possible_types
    hack_is_needed = (type == 'application/x-ole-storage' && types.include?(FILE_TYPE_TO_HAC))
    return types.first if hack_is_needed
    type
  end
end

Paperclip::ContentTypeDetector.send(:prepend, ContentTypeDecectorHack)
```

**Comment by roooodcastro** [comment]
Having the same issue. All my PaperClip related spec are failing because of this.

A fork of @siannopollo's hack worked for me:

```ruby
    Paperclip::ContentTypeDetector.class_eval do
      def type_from_file_contents_with_excel_exception
        type = type_from_file_contents_without_excel_exception
        types = possible_types
        return 'application/vnd.ms-excel' if type == 'application/x-ole-storage' && types.include?('application/vnd.ms-excel')
        type
      end
      alias_method_chain :type_from_file_contents, :excel_exception
    end

**Comment by peq102** [comment]
@bewatts, your solution isn't working for me (cannot use the others as I'm using rails 5.1.3). Can you suggest anything? I get the following error.

`NameError: undefined local variable or method `type' for #<Paperclip::ContentTypeDetector:0xf96d9d0>`

In the alias_method_chain snippets, type is defined. But, isn't in the prepend snippet. Should it be defined by Paperclip? I saved the snippet to `config/application.rb`. Perhaps that is my issue?

**Comment by ajw725** [comment]
Same problem here. Haven't quite figured out how I'm going to resolve it yet - I don't just want to assume that all x-ole-storage files are .xls, so I might check a system call to `file` - but mostly just wanted to add another report to the issue.

**Comment by dougc84** [comment]
Had an issue with a word doc reporting `application/x-ole-storage`.  Throwing my name in the ring as someone else having this issue.

**Comment by dukz** [comment]
For anyone using Rails 5, here's a code using Module#prepend. I've added it into a `config/initializers/patch_paperclip_content_type_detector.rb`

```ruby
module PatchPaperclipContentTypeDetector
  def type_from_file_contents
    type = super
    types = possible_types
    return 'application/vnd.ms-excel' if type == 'application/x-ole-storage' && types.include?('application/vnd.ms-excel')
    type
  end
end

Paperclip::ContentTypeDetector.class_eval do
  prepend PatchPaperclipContentTypeDetector
end
```

**Comment by matt-grimm** [comment]
Until this issue is resolved, you can make an `IO` call to check for file type. 
Assume `file_path` points towards an `xls` file for the example below.
```
type = IO.popen(["file", "--mime-type", "--brief", "file_path") { |io| io.read.chomp.to_s }
=> "application/vnd.ms-excel"
```

**Comment by jigarbhatt2711** [comment]
> Same this is happening to `.doc` files
> 
> ```
> [5] pry(main)> MimeMagic.by_magic(File.open('/users/pivotal/Documents/test.doc'))
> => #<MimeMagic:0x007fdb3eb8f008 @mediatype="application", @subtype="x-ole-storage", @type="application/x-ole-storage">
> [6] pry(main)> MimeMagic.by_path('/users/pivotal/Documents/test.doc')
> => #<MimeMagic:0x007fdb3eb345e0 @mediatype="application", @subtype="msword", @type="application/msword">
> ```

This solution is working.Thanks a lot!!

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
