### ISSUE TITLE
by_magic identifies a PDF as spreadsheetml

### ISSUE THREAD

**Issue by pkqk** [minad/mimemagic#51]
We've found a few pdfs we generated get miss identified as `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` by `MimeMagic.by_magic`.

It seems to be because of the pattern in [overlay.rb](https://github.com/minad/mimemagic/blob/master/lib/mimemagic/overlay.rb#L4) that checks if `xl/` appears in the first 5000 bytes.

I can't attach the whole pdf as it contains private information but this is the first 5000 bytes [head.pdf](https://github.com/minad/mimemagic/files/909542/head.pdf)

perhaps it should prefer explicit file starting blocks before moving to the guessing?

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
