### ISSUE TITLE
Text files not recognised by magic

### ISSUE THREAD

**Issue by WalterS** [minad/mimemagic#57]
Somehow plaintext files are not recognised:
```ruby
irb>> MimeMagic::VERSION
=> "0.3.2"
irb>> file = '/tmp/foo'
=> "/tmp/foo"
irb>> File.write(file, 'This is a text file')
=> 19
irb>> MimeMagic.by_magic(file)
=> nil
```

**Comment by georgechang0117** [comment]
I've got the same problem.

**Comment by jonnynux** [comment]
I've got the same problem.

**Comment by jonnynux** [comment]
I confirm the issue, every plain textual file like csv, json, css, txt are not recognized. The workaround is to return text/plain if the result of by_magic is nil, but this will make some side effects (example for application/octet-stream. Other suggestions?

**Comment by jamesremuscat** [comment]
It appears to [only detect text files by magic if the files begin with the strings](https://github.com/minad/mimemagic/blob/master/lib/mimemagic/tables.rb#L1998):
- `This is TeX,`; or
- `This is METAFONT,`

Needless to say, this would only appear to cover a minimal subset of text files.

**Comment by seabre** [comment]
I have a proposed PR for testing for CSVs: #75

**Comment by minad** [comment]
Is it possible to test via file extension and then via magic? This should handle the tex, json, css, csv cases.

**Comment by seabre** [comment]
If you want to be able to match and be mostly sure, you _have_ to parse at least part of the file. I'm not sure with the current setup that you actually can correctly check for CSVs, JSON, CSS, and etc. You _can_ check by extension, but I can do that without the library.

**Comment by kelly-croswell** [comment]
Has any movement been made on this? I just ran into this problem on a project I'm working on and could really use a solution.

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
