### ISSUE TITLE
Changing bacon to rspec

### ISSUE THREAD

**Issue by junaruga** [minad/mimemagic#60]
Right now this project is using the small RSpec clone `bacon`.
But the problem is that `bacon` project stopped the development [1].
I wanted to fix a issue for that in a past time. But I could not.

So, I think changing this project's testing framework from `bacon` to `rspec` would be better.
If you like it, I can contribute for that.

[1] https://github.com/chneukirchen/bacon/issues/32

**Comment by junaruga** [comment]
Or changing to `minitest`.
Nowadays `minitest` or `rspec` are popular.
But in this case. changing `bacon` to `rspec` is easier.
How do you think?

**Comment by minad** [comment]
Hey Jun,

you are right about bacon. How much are you interested in this gem? If you want to become a co-maintainer, please let me know :) Unfortunately I don't have much time to maintain it right now.

Daniel

**Comment by minad** [comment]
@junaruga Ah you already wrote that you would like to contribute it, is it ok if I add you to the repository?

**Comment by junaruga** [comment]
@minad Okay, I am happy to be the co-maintainer.
Because `mimemagic` is a part of Rails 5.2.0 runtime dependency now.
I am working to release Rails 5.2.0 gem for Fedora Project.
That's my motivation :)
