### ISSUE TITLE
0.3.1 -> 0.3.2 upgrade causes .dcm file with embedded pdf to come back as application/pdf

### ISSUE THREAD

**Issue by sbsurf** [minad/mimemagic#63]
Upgrading from 0.3.1 to 0.3.2 returns `pdf` mime type (`application/pdf`) for a `.dcm` file (`application/dicom`). The `.dcm` file does have an embedded pdf in it. Did the version bump include some sort of logic to cause this?

**Comment by nspence** [comment]
I was able to correct this by adding the following to a Rails initializer:

`MimeMagic.add('application/dicom', magic: [[128, 'DICM']])`

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
