### ISSUE TITLE
Wrong mime for some files

### ISSUE THREAD

**Issue by jonnynux** [minad/mimemagic#69]
* test.ppt : **application/x-ole-storage** this must be a **application/vnd.ms-powerpoint**
* test.pps : **application/x-ole-storage** this must be a **application/vnd.ms-powerpoint**
* test.ppsx : **application/vnd.openxmlformats-officedocument.presentationml.presentation** this must be a **application/vnd.openxmlformats-officedocument.presentationml.slideshow**
* test.xls : **application/x-ole-storage** this must be a **application/vnd.ms-excel**

Someone can explain me how to write a custom mime type to add? Especially i don't understand what does means the first part (eg. [0, "PK\003\004"...).

**Comment by BKSpurgeon** [comment]
@jonnynux perhaps you've already solved this particular problem, but another option could be to use (marcel)[https://github.com/basecamp/marcel] which wraps a lot of the difficult associated with MS office documents.

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
