### ISSUE TITLE
Release a new version with PR #39

### ISSUE THREAD

**Issue by flaprano** [minad/mimemagic#77]
XLSX files saved by Google Spreadsheet and OpenOffice/LibreOffice are being recognized as application/zip na versão 0.3.3

Checking the PRs and the problems I found the PR #39 that fixed (or tried) this problem and is already merged in master but yet not released.
Please generate a new version with this fix.

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
