### ISSUE TITLE
Wrong Website URL for the project.

### ISSUE THREAD

**Issue by akiko-pusu** [minad/mimemagic#82]
Thanks for this useful library!
The website URL at the top of this repository seems to be incorrect.

The current settings are as follows:
```
Mime type detection in ruby via file extension or file content 
https://rdoc.info/github/minad/mimemagic/frames/file/README.md
```
After clicking on the above website, I saw a 404 error page. ("We Couldn't Find That Page")

ASIS:  https://rdoc.info/github/minad/mimemagic/frames/file/README.md 
Maybe: https://rdoc.info/github/minad/mimemagic

I hope this will be of some help.

**Comment by minad** [comment]
Fixed.
