### ISSUE TITLE
RTF files comment is blank

### ISSUE THREAD

**Issue by Hamdan85** [minad/mimemagic#83]
`MimeMagic.by_magic(File.open('./test.rtf', 'r'))` returns 'application/rtf' but it should also accept 'text/rtf', which, for example, is used by filestack... 

the problem is that `MimeMagic.new("text/rtf").comment` returns "" which can cause some trouble.

I don't know if it's supposed to be this way so feel free to close the bug... 

PS: I think this is related to https://github.com/minad/mimemagic/issues/69 (which I also can reproduce)

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
