### ISSUE TITLE
xlsx support

### ISSUE THREAD

**Issue by farrokhpey** [minad/mimemagic#86]
I'm using carrierwave-aws and mimemagic latest version, now when upload a xlsx file in s3 everything is OK and file will be uploaded to s3, but when i try to download it, a zip file startdownloading, as i know the content type of file may be wrong,
now could you please tell me how can i set correct mime type for xlsx file while uploading using CarrierWave::Uploader::Base config

**Comment by gmonein** [comment]
Hello,

I've just fixed an issue with content_type through this: https://github.com/minad/mimemagic/issues/39#issuecomment-323940672

This may help you

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
