### ISSUE TITLE
Add support for BMP

### ISSUE THREAD

**Issue by gmonein** [minad/mimemagic#91]
Hello,

`MimeMagic.by_magic(bmp_file)` respond me `invalid/invalid` content_type
when `file --mime-type -b bmp_file` respond me `image/bmp`

I've found a workaround by doing this:
```ruby
[ [ 'image/bmp',
    { magic: [[0, "BM", [[0..2, 'BM']]]], extensions: %w[bmp], parents: %w[], comment: 'BMP' } ]
].each do |magic|
  MimeMagic.add(*magic)
end
```
(if someone can check the validity of this for me)

If you (little github user) encounter content_type invalid/invalid issues, I've found the solution on wikipedia:
https://en.wikipedia.org/wiki/List_of_file_signatures

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
