### ISSUE TITLE
Zip files with pdfs unexpectedly returning application/pdf instead of application/zip

### ISSUE THREAD

**Issue by benkoshy** [minad/mimemagic#93]
### Explanation of the problem

- I have a .zip file which contains .pdf files and .dwg files.

### Expected Behaviour
- ` MimeMagic.by_magic(File.read(path_to_zip_file)).to_s` should return `application/zip`.

### Actual Behaviour
- ` MimeMagic.by_magic(File.read(path_to_zip_file)).to_s` returns `application/pdf`. This is completely unexpected. It should return zip, instead of pdf.

### Reproducible test
- Please clone the repository here and run the tests: `rake test`: https://github.com/BKSpurgeon/mimemagic/tree/fix-zip-file-bug
- Please use the fix-zip-file-bug branch.
- You should see the test fail.

Any pointers in the right direction would be much appreciate. I'd be happy to make a PR.

chrs

Ben

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.
