### ISSUE TITLE
 freedesktop.org.xml file license

### ISSUE THREAD

**Issue by hadess** [minad/mimemagic#97]
I've historically been the maintainer of shared-mime-info for around 15 years, and script/freedesktop.org.xml looks like it's a copy of the database shipped with shared-mime-info, which is released under the GPL, with shared-mime-info's translators work merged in, and the GPL header removed.
The license that you're shipping mimemagic under (MIT) isn't compatible with shared-mime-info's.
There are a number of possibilities to fix this problem:
- change the mimemagic license to be GPL compatible
- parse the XML file that shared-mime-info ships at runtime, and don't ship it in a codebase with an incompatible license

Using a GPL file as a source makes your whole codebase a derived work, making it all GPL, so I think it's pretty important that this problem gets corrected before somebody uses it in a pure MIT codebase, or a closed-source application.

You will also need to re-add the GPL header to the shared-mime-info XML file as a matter of urgency. It was stripped in release tarballs by the tool used to merge translations, but is visible in the `.in` version of the same file.

**Comment by minad** [comment]
Thank you for notifying me. I changed the license of the project to GPLv2.

**Comment by hadess** [comment]
Thanks a lot for responding this quickly, and the swift resolution, much appreciated :)

**Comment by icbd** [comment]
> * change the mimemagic license to be GPL compatible
> * parse the XML file that shared-mime-info ships at runtime, and don't ship it in a codebase with an incompatible license


`https://github.com/mimemagicrb/mimemagic/commit/641561de3f2451dde562ab90279658b5a3efcf08`

So did this [commit](https://github.com/mimemagicrb/mimemagic/commit/641561de3f2451dde562ab90279658b5a3efcf08) adopt option two?

I have a question to ask, does the license agreement only restrict the code?
If we put this GLP file as data in a zip package and commit the zip package to this repo, do we also need to declare this repo as GLP?
If we put this GLP file as data in another repo, and download this file when installing this gem, does this repo have to be declared as GLP?

Thanks!

@hadess @minad
